# .github/workflows/pages.yml
name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master   # o main, según tu rama principal

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build Angular app
        run: npm run build -- --configuration production --output-path docs --base-href=/

      - name: Flatten docs folder
        run: |
          mv docs/browser/* docs/
          rm -rf docs/browser

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # ← aquí indicas el environment que Pages necesita
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

